table dimblade
	lineageTag: 50000001-0001-0001-0001-000000000001

	measure 'Blade Count' = COUNTROWS(dimblade)
		displayFolder: Measures
		lineageTag: 50000001-0001-0001-0001-100000000001

	column BladeId
		dataType: string
		summarizeBy: none
		sourceColumn: BladeId
		lineageTag: 50000001-0001-0001-0001-200000000001

		annotation SummarizationSetBy = Automatic

	column BladeName
		dataType: string
		summarizeBy: none
		sourceColumn: BladeName
		lineageTag: 50000001-0001-0001-0001-200000000002

		annotation SummarizationSetBy = Automatic

	column TurbineId
		dataType: string
		summarizeBy: none
		sourceColumn: TurbineId
		lineageTag: 50000001-0001-0001-0001-200000000003

		annotation SummarizationSetBy = Automatic

	column BladePosition
		dataType: string
		summarizeBy: none
		sourceColumn: BladePosition
		lineageTag: 50000001-0001-0001-0001-200000000004

		annotation SummarizationSetBy = Automatic

	column LengthM
		dataType: double
		summarizeBy: none
		sourceColumn: LengthM
		lineageTag: 50000001-0001-0001-0001-200000000005

		annotation SummarizationSetBy = Automatic

	column Material
		dataType: string
		summarizeBy: none
		sourceColumn: Material
		lineageTag: 50000001-0001-0001-0001-200000000006

		annotation SummarizationSetBy = Automatic

	column Manufacturer
		dataType: string
		summarizeBy: none
		sourceColumn: Manufacturer
		lineageTag: 50000001-0001-0001-0001-200000000007

		annotation SummarizationSetBy = Automatic

	column InstallDate
		dataType: string
		summarizeBy: none
		sourceColumn: InstallDate
		lineageTag: 50000001-0001-0001-0001-200000000008

		annotation SummarizationSetBy = Automatic

	column LastInspectionDate
		dataType: string
		summarizeBy: none
		sourceColumn: LastInspectionDate
		lineageTag: 50000001-0001-0001-0001-200000000009

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		summarizeBy: none
		sourceColumn: Status
		lineageTag: 50000001-0001-0001-0001-200000000010

		annotation SummarizationSetBy = Automatic

	partition dimblade = entity
		mode: directLake
		entityName: dimblade
		expressionSource: DatabaseQuery

	annotation PBI_ResultType = Table
