table dimsensor
	lineageTag: 50000003-0001-0001-0001-000000000001

	measure 'Sensor Count' = COUNTROWS(dimsensor)
		displayFolder: Measures
		lineageTag: 50000003-0001-0001-0001-100000000001

	column SensorId
		dataType: string
		summarizeBy: none
		sourceColumn: SensorId
		lineageTag: 50000003-0001-0001-0001-200000000001

		annotation SummarizationSetBy = Automatic

	column SensorName
		dataType: string
		summarizeBy: none
		sourceColumn: SensorName
		lineageTag: 50000003-0001-0001-0001-200000000002

		annotation SummarizationSetBy = Automatic

	column TurbineId
		dataType: string
		summarizeBy: none
		sourceColumn: TurbineId
		lineageTag: 50000003-0001-0001-0001-200000000003

		annotation SummarizationSetBy = Automatic

	column SensorType
		dataType: string
		summarizeBy: none
		sourceColumn: SensorType
		lineageTag: 50000003-0001-0001-0001-200000000004

		annotation SummarizationSetBy = Automatic

	column Location
		dataType: string
		summarizeBy: none
		sourceColumn: Location
		lineageTag: 50000003-0001-0001-0001-200000000005

		annotation SummarizationSetBy = Automatic

	column Unit
		dataType: string
		summarizeBy: none
		sourceColumn: Unit
		lineageTag: 50000003-0001-0001-0001-200000000006

		annotation SummarizationSetBy = Automatic

	column MinThreshold
		dataType: double
		summarizeBy: none
		sourceColumn: MinThreshold
		lineageTag: 50000003-0001-0001-0001-200000000007

		annotation SummarizationSetBy = Automatic

	column MaxThreshold
		dataType: double
		summarizeBy: none
		sourceColumn: MaxThreshold
		lineageTag: 50000003-0001-0001-0001-200000000008

		annotation SummarizationSetBy = Automatic

	column InstallDate
		dataType: string
		summarizeBy: none
		sourceColumn: InstallDate
		lineageTag: 50000003-0001-0001-0001-200000000009

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		summarizeBy: none
		sourceColumn: Status
		lineageTag: 50000003-0001-0001-0001-200000000010

		annotation SummarizationSetBy = Automatic

	partition dimsensor = entity
		mode: directLake
		entityName: dimsensor
		expressionSource: DatabaseQuery

	annotation PBI_ResultType = Table
