table factpoweroutput
	lineageTag: 50000012-0001-0001-0001-000000000001

	measure 'Output Record Count' = COUNTROWS(factpoweroutput)
		displayFolder: Measures
		lineageTag: 50000012-0001-0001-0001-100000000001

	measure 'Total Power Output KW' = SUM(factpoweroutput[PowerOutputKW])
		formatString: #,0
		displayFolder: Measures
		lineageTag: 50000012-0001-0001-0001-100000000002

	measure 'Avg Capacity Factor' = AVERAGE(factpoweroutput[CapacityFactor])
		formatString: 0.00%
		displayFolder: Measures
		lineageTag: 50000012-0001-0001-0001-100000000003

	measure 'Avg Wind Speed Ms' = AVERAGE(factpoweroutput[WindSpeedMs])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 50000012-0001-0001-0001-100000000004

	column OutputId
		dataType: string
		summarizeBy: none
		sourceColumn: OutputId
		lineageTag: 50000012-0001-0001-0001-200000000001

		annotation SummarizationSetBy = Automatic

	column TurbineId
		dataType: string
		summarizeBy: none
		sourceColumn: TurbineId
		lineageTag: 50000012-0001-0001-0001-200000000002

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: string
		summarizeBy: none
		sourceColumn: Date
		lineageTag: 50000012-0001-0001-0001-200000000003

		annotation SummarizationSetBy = Automatic

	column Hour
		dataType: double
		summarizeBy: none
		sourceColumn: Hour
		lineageTag: 50000012-0001-0001-0001-200000000004

		annotation SummarizationSetBy = Automatic

	column WindSpeedMs
		dataType: double
		summarizeBy: none
		sourceColumn: WindSpeedMs
		lineageTag: 50000012-0001-0001-0001-200000000005

		annotation SummarizationSetBy = Automatic

	column PowerOutputKW
		dataType: double
		summarizeBy: none
		sourceColumn: PowerOutputKW
		lineageTag: 50000012-0001-0001-0001-200000000006

		annotation SummarizationSetBy = Automatic

	column CapacityFactor
		dataType: double
		summarizeBy: none
		sourceColumn: CapacityFactor
		lineageTag: 50000012-0001-0001-0001-200000000007

		annotation SummarizationSetBy = Automatic

	column RotorRPM
		dataType: double
		summarizeBy: none
		sourceColumn: RotorRPM
		lineageTag: 50000012-0001-0001-0001-200000000008

		annotation SummarizationSetBy = Automatic

	column PitchAngleDeg
		dataType: double
		summarizeBy: none
		sourceColumn: PitchAngleDeg
		lineageTag: 50000012-0001-0001-0001-200000000009

		annotation SummarizationSetBy = Automatic

	column YawAngleDeg
		dataType: double
		summarizeBy: none
		sourceColumn: YawAngleDeg
		lineageTag: 50000012-0001-0001-0001-200000000010

		annotation SummarizationSetBy = Automatic

	column GridFrequencyHz
		dataType: double
		summarizeBy: none
		sourceColumn: GridFrequencyHz
		lineageTag: 50000012-0001-0001-0001-200000000011

		annotation SummarizationSetBy = Automatic

	partition factpoweroutput = entity
		mode: directLake
		entityName: factpoweroutput
		expressionSource: DatabaseQuery

	annotation PBI_ResultType = Table
