table dimemployee
	lineageTag: 10000009-0001-0001-0001-000000000001

	measure 'Employee Count' = COUNTROWS(dimemployee)
		displayFolder: Measures
		lineageTag: 10000009-0001-0001-0001-100000000001

	measure 'Active Employee Count' = CALCULATE(COUNTROWS(dimemployee), dimemployee[Status] = "Active")
		displayFolder: Measures
		lineageTag: 10000009-0001-0001-0001-100000000002

	column EmployeeId
		dataType: string
		summarizeBy: none
		sourceColumn: EmployeeId
		lineageTag: 10000009-0001-0001-0001-200000000001

		annotation SummarizationSetBy = Automatic

	column FirstName
		dataType: string
		summarizeBy: none
		sourceColumn: FirstName
		lineageTag: 10000009-0001-0001-0001-200000000002

		annotation SummarizationSetBy = Automatic

	column LastName
		dataType: string
		summarizeBy: none
		sourceColumn: LastName
		lineageTag: 10000009-0001-0001-0001-200000000003

		annotation SummarizationSetBy = Automatic

	column Role
		dataType: string
		summarizeBy: none
		sourceColumn: Role
		lineageTag: 10000009-0001-0001-0001-200000000004

		annotation SummarizationSetBy = Automatic

	column Department
		dataType: string
		summarizeBy: none
		sourceColumn: Department
		lineageTag: 10000009-0001-0001-0001-200000000005

		annotation SummarizationSetBy = Automatic

	column RefineryId
		dataType: string
		summarizeBy: none
		sourceColumn: RefineryId
		lineageTag: 10000009-0001-0001-0001-200000000006

		annotation SummarizationSetBy = Automatic

	column HireDate
		dataType: string
		summarizeBy: none
		sourceColumn: HireDate
		lineageTag: 10000009-0001-0001-0001-200000000007

		annotation SummarizationSetBy = Automatic

	column CertificationLevel
		dataType: string
		summarizeBy: none
		sourceColumn: CertificationLevel
		lineageTag: 10000009-0001-0001-0001-200000000008

		annotation SummarizationSetBy = Automatic

	column ShiftPattern
		dataType: string
		summarizeBy: none
		sourceColumn: ShiftPattern
		lineageTag: 10000009-0001-0001-0001-200000000009

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		summarizeBy: none
		sourceColumn: Status
		lineageTag: 10000009-0001-0001-0001-200000000010

		annotation SummarizationSetBy = Automatic

	partition dimemployee = entity
		mode: directLake
		entityName: dimemployee
		expressionSource: DatabaseQuery

	annotation PBI_ResultType = Table
