table dimpipeline
	lineageTag: 10000004-0001-0001-0001-000000000001

	measure 'Pipeline Count' = COUNTROWS(dimpipeline)
		displayFolder: Measures
		lineageTag: 10000004-0001-0001-0001-100000000001

	measure 'Total Max Flow BPD' = SUM(dimpipeline[MaxFlowBPD])
		formatString: #,0
		displayFolder: Measures
		lineageTag: 10000004-0001-0001-0001-100000000002

	column PipelineId
		dataType: string
		summarizeBy: none
		sourceColumn: PipelineId
		lineageTag: 10000004-0001-0001-0001-200000000001

		annotation SummarizationSetBy = Automatic

	column PipelineName
		dataType: string
		summarizeBy: none
		sourceColumn: PipelineName
		lineageTag: 10000004-0001-0001-0001-200000000002

		annotation SummarizationSetBy = Automatic

	column FromProcessUnitId
		dataType: string
		summarizeBy: none
		sourceColumn: FromProcessUnitId
		lineageTag: 10000004-0001-0001-0001-200000000003

		annotation SummarizationSetBy = Automatic

	column ToProcessUnitId
		dataType: string
		summarizeBy: none
		sourceColumn: ToProcessUnitId
		lineageTag: 10000004-0001-0001-0001-200000000004

		annotation SummarizationSetBy = Automatic

	column RefineryId
		dataType: string
		summarizeBy: none
		sourceColumn: RefineryId
		lineageTag: 10000004-0001-0001-0001-200000000005

		annotation SummarizationSetBy = Automatic

	column DiameterInches
		dataType: double
		summarizeBy: none
		sourceColumn: DiameterInches
		lineageTag: 10000004-0001-0001-0001-200000000006

		annotation SummarizationSetBy = Automatic

	column LengthFeet
		dataType: double
		summarizeBy: none
		sourceColumn: LengthFeet
		lineageTag: 10000004-0001-0001-0001-200000000007

		annotation SummarizationSetBy = Automatic

	column Material
		dataType: string
		summarizeBy: none
		sourceColumn: Material
		lineageTag: 10000004-0001-0001-0001-200000000008

		annotation SummarizationSetBy = Automatic

	column MaxFlowBPD
		dataType: int64
		summarizeBy: sum
		sourceColumn: MaxFlowBPD
		lineageTag: 10000004-0001-0001-0001-200000000009

		annotation SummarizationSetBy = Automatic

	column InstalledDate
		dataType: string
		summarizeBy: none
		sourceColumn: InstalledDate
		lineageTag: 10000004-0001-0001-0001-200000000010

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		summarizeBy: none
		sourceColumn: Status
		lineageTag: 10000004-0001-0001-0001-200000000011

		annotation SummarizationSetBy = Automatic

	partition dimpipeline = entity
		mode: directLake
		entityName: dimpipeline
		expressionSource: DatabaseQuery

	annotation PBI_ResultType = Table
