# Fabric Notebook: Load Smart Building CSV Data into Delta Tables
# Auto-generated by Generate-SemanticModels.ps1 for the Smart Building domain.
# Reads CSV files from the lakehouse Files/ folder and writes typed Delta tables.

from pyspark.sql import SparkSession
from pyspark.sql.types import *

# ============================================================================
# Table definitions: (csv_filename, table_name, schema)
# ============================================================================

TABLE_DEFINITIONS = [
    (
        "DimBuilding.csv", "dimbuilding",
        StructType([
            StructField("BuildingId", StringType(), False),
            StructField("BuildingName", StringType(), True),
            StructField("Address", StringType(), True),
            StructField("City", StringType(), True),
            StructField("Country", StringType(), True),
            StructField("Floors", DoubleType(), True),
            StructField("TotalAreaSqFt", DoubleType(), True),
            StructField("YearBuilt", StringType(), True),
            StructField("BuildingType", StringType(), True),
            StructField("Status", StringType(), True),
            StructField("Owner", StringType(), True),
        ])
    ),
    (
        "DimFloor.csv", "dimfloor",
        StructType([
            StructField("FloorId", StringType(), False),
            StructField("FloorName", StringType(), True),
            StructField("BuildingId", StringType(), True),
            StructField("FloorNumber", DoubleType(), True),
            StructField("AreaSqFt", DoubleType(), True),
            StructField("ZoneCount", DoubleType(), True),
            StructField("Status", StringType(), True),
        ])
    ),
    (
        "DimZone.csv", "dimzone",
        StructType([
            StructField("ZoneId", StringType(), False),
            StructField("ZoneName", StringType(), True),
            StructField("FloorId", StringType(), True),
            StructField("ZoneType", StringType(), True),
            StructField("AreaSqFt", DoubleType(), True),
            StructField("MaxOccupancy", DoubleType(), True),
            StructField("Status", StringType(), True),
        ])
    ),
    (
        "DimSensor.csv", "dimsensor",
        StructType([
            StructField("SensorId", StringType(), False),
            StructField("SensorName", StringType(), True),
            StructField("SensorType", StringType(), True),
            StructField("ZoneId", StringType(), True),
            StructField("MeasurementUnit", StringType(), True),
            StructField("MinRange", DoubleType(), True),
            StructField("MaxRange", DoubleType(), True),
            StructField("InstallDate", StringType(), True),
            StructField("Status", StringType(), True),
            StructField("Manufacturer", StringType(), True),
        ])
    ),
    (
        "DimHVACSystem.csv", "dimhvacsystem",
        StructType([
            StructField("HVACId", StringType(), False),
            StructField("HVACName", StringType(), True),
            StructField("ZoneId", StringType(), True),
            StructField("HVACType", StringType(), True),
            StructField("CapacityBTU", DoubleType(), True),
            StructField("Manufacturer", StringType(), True),
            StructField("Model", StringType(), True),
            StructField("InstallDate", StringType(), True),
            StructField("Status", StringType(), True),
            StructField("EnergyRating", StringType(), True),
        ])
    ),
    (
        "DimLightingSystem.csv", "dimlightingsystem",
        StructType([
            StructField("LightingId", StringType(), False),
            StructField("LightingName", StringType(), True),
            StructField("ZoneId", StringType(), True),
            StructField("LightingType", StringType(), True),
            StructField("WattageTotalW", DoubleType(), True),
            StructField("BulbCount", DoubleType(), True),
            StructField("InstallDate", StringType(), True),
            StructField("Status", StringType(), True),
        ])
    ),
    (
        "DimAccessPoint.csv", "dimaccesspoint",
        StructType([
            StructField("AccessPointId", StringType(), False),
            StructField("AccessPointName", StringType(), True),
            StructField("ZoneId", StringType(), True),
            StructField("AccessPointType", StringType(), True),
            StructField("Protocol", StringType(), True),
            StructField("CoverageAreaSqFt", DoubleType(), True),
            StructField("Manufacturer", StringType(), True),
            StructField("Status", StringType(), True),
        ])
    ),
    (
        "DimOccupant.csv", "dimoccupant",
        StructType([
            StructField("OccupantId", StringType(), False),
            StructField("FullName", StringType(), True),
            StructField("Department", StringType(), True),
            StructField("ZoneId", StringType(), True),
            StructField("AccessLevel", StringType(), True),
            StructField("BadgeId", StringType(), True),
            StructField("Status", StringType(), True),
        ])
    ),
    (
        "DimElevator.csv", "dimelevator",
        StructType([
            StructField("ElevatorId", StringType(), False),
            StructField("ElevatorName", StringType(), True),
            StructField("BuildingId", StringType(), True),
            StructField("ElevatorType", StringType(), True),
            StructField("CapacityLbs", DoubleType(), True),
            StructField("MaxFloors", DoubleType(), True),
            StructField("Manufacturer", StringType(), True),
            StructField("InstallDate", StringType(), True),
            StructField("Status", StringType(), True),
        ])
    ),
    (
        "DimEnergyMeter.csv", "dimenergymeter",
        StructType([
            StructField("MeterId", StringType(), False),
            StructField("MeterName", StringType(), True),
            StructField("BuildingId", StringType(), True),
            StructField("MeterType", StringType(), True),
            StructField("MeasurementUnit", StringType(), True),
            StructField("InstallDate", StringType(), True),
            StructField("Status", StringType(), True),
        ])
    ),
    (
        "FactAlert.csv", "factalert",
        StructType([
            StructField("AlertId", StringType(), False),
            StructField("SensorId", StringType(), True),
            StructField("AlertType", StringType(), True),
            StructField("Severity", StringType(), True),
            StructField("AlertTimestamp", StringType(), True),
            StructField("AcknowledgedTimestamp", StringType(), True),
            StructField("AlertValue", DoubleType(), True),
            StructField("ThresholdValue", DoubleType(), True),
            StructField("Description", StringType(), True),
            StructField("Status", StringType(), True),
        ])
    ),
    (
        "FactMaintenanceTicket.csv", "factmaintenanceticket",
        StructType([
            StructField("TicketId", StringType(), False),
            StructField("EquipmentType", StringType(), True),
            StructField("EquipmentId", StringType(), True),
            StructField("TicketType", StringType(), True),
            StructField("Priority", StringType(), True),
            StructField("AssignedToOccupantId", StringType(), True),
            StructField("CreatedDate", StringType(), True),
            StructField("ResolvedDate", StringType(), True),
            StructField("DurationHours", DoubleType(), True),
            StructField("CostUSD", DoubleType(), True),
            StructField("Description", StringType(), True),
            StructField("Status", StringType(), True),
        ])
    ),
    (
        "SensorTelemetry.csv", "sensortelemetry",
        StructType([
            StructField("ReadingId", StringType(), False),
            StructField("SensorId", StringType(), True),
            StructField("Timestamp", StringType(), True),
            StructField("ReadingValue", DoubleType(), True),
            StructField("QualityFlag", StringType(), True),
            StructField("IsAnomaly", StringType(), True),
        ])
    ),
]

# ============================================================================
# Load CSV files into Delta tables
# ============================================================================

spark = SparkSession.builder.getOrCreate()
files_path = "Files"

success_count = 0
error_count = 0

for csv_file, table_name, schema in TABLE_DEFINITIONS:
    try:
        file_path = f"{files_path}/{csv_file}"
        print(f"\n{'='*60}")
        print(f"Loading: {csv_file} -> table '{table_name}'")
        print(f"{'='*60}")

        df = spark.read.format("csv") \
            .option("header", "true") \
            .option("inferSchema", "false") \
            .schema(schema) \
            .load(file_path)

        row_count = df.count()
        print(f"  Rows read: {row_count}")
        print(f"  Columns: {', '.join(df.columns)}")

        df.write.format("delta") \
            .mode("overwrite") \
            .option("overwriteSchema", "true") \
            .saveAsTable(table_name)

        print(f"  OK: Table '{table_name}' created with {row_count} rows")
        success_count += 1
    except Exception as e:
        print(f"  ERROR loading {csv_file}: {e}")
        error_count += 1

print(f"\n{'='*60}")
print(f"Smart Building Load Complete: {success_count} succeeded, {error_count} failed")
print(f"{'='*60}")
