param([Parameter(Mandatory=$true)][string]$WorkspaceId, [Parameter(Mandatory=$true)][string]$KqlDatabaseId, [Parameter(Mandatory=$true)][string]$QueryServiceUri, [string]$DashboardName = 'EnterpriseFinanceHRDashboard')
$ErrorActionPreference = 'Stop'
$token = (Get-AzAccessToken -ResourceUrl 'https://api.fabric.microsoft.com').Token; $headers = @{ Authorization = "Bearer $token"; 'Content-Type' = 'application/json' }; $baseUri = 'https://api.fabric.microsoft.com/v1'
$database = Invoke-RestMethod -Uri "$baseUri/workspaces/$WorkspaceId/kqlDatabases/$KqlDatabaseId" -Headers $headers
$sourceId = [guid]::NewGuid().ToString(); $pageId = [guid]::NewGuid().ToString()
$queries = @('FinanceVariance | summarize Variance = sum(VarianceAmount) by CostCenterId','PayrollCostAnomaly | where Severity in ("High", "Critical") | order by Timestamp desc','WorkforceMovement | summarize Movement = sum(MovementCount) by FiscalPeriodId, MovementType','ForecastFreshness | summarize MaxAgeHours = max(AgeHours) by CostCenterId','PlanningException | where Severity in ("High", "Critical") | order by Timestamp desc')
$tiles = @(); $queryObjects = @(); $titles = @('Budget variance','Payroll cost anomaly','Workforce movement','Forecast freshness','Planning exceptions')
for ($index = 0; $index -lt $queries.Count; $index++) { $queryId = [guid]::NewGuid().ToString(); $queryObjects += @{ id = $queryId; text = $queries[$index]; dataSource = @{ kind = 'inline'; dataSourceId = $sourceId }; usedVariables = @() }; $tiles += @{ id = [guid]::NewGuid().ToString(); title = $titles[$index]; layout = @{ x = ($index % 2) * 12; y = [Math]::Floor($index / 2) * 6; width = 12; height = 6 }; pageId = $pageId; visualType = if ($index -eq 0 -or $index -eq 2) { 'line' } else { 'table' }; visualOptions = @{}; queryRef = @{ kind = 'query'; queryId = $queryId } } }
$dashboard = @{ schema_version = '52'; title = $DashboardName; autoRefresh = @{ enabled = $true; defaultInterval = '30s'; minInterval = '10s' }; dataSources = @(@{ id = $sourceId; scopeId = 'kusto'; name = $database.displayName; clusterUri = $QueryServiceUri; database = $database.displayName; kind = 'manual-kusto' }); pages = @(@{ id = $pageId; name = 'Finance and HR planning' }); tiles = $tiles; queries = $queryObjects; baseQueries = @(); parameters = @() }
$payload = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes(($dashboard | ConvertTo-Json -Depth 20 -Compress)))
$existing = ((Invoke-RestMethod -Uri "$baseUri/workspaces/$WorkspaceId/items?type=KQLDashboard" -Headers $headers).value | Where-Object { $_.displayName -eq $DashboardName } | Select-Object -First 1)
$definition = @{ parts = @(@{ path = 'RealTimeDashboard.json'; payload = $payload; payloadType = 'InlineBase64' }) }
if ($existing) { Invoke-RestMethod -Method Post -Uri "$baseUri/workspaces/$WorkspaceId/kqlDashboards/$($existing.id)/updateDefinition" -Headers $headers -Body (@{ definition = $definition } | ConvertTo-Json -Depth 20) | Out-Null } else { Invoke-RestMethod -Method Post -Uri "$baseUri/workspaces/$WorkspaceId/items" -Headers $headers -Body (@{ displayName = $DashboardName; type = 'KQLDashboard'; definition = $definition } | ConvertTo-Json -Depth 20) | Out-Null }
Write-Host "KQL dashboard '$DashboardName' deployed with planning safety signals." -ForegroundColor Green