table factlabresult
	lineageTag: 40000010-0001-0001-0001-000000000001

	measure 'Lab Result Count' = COUNTROWS(factlabresult)
		displayFolder: Measures
		lineageTag: 40000010-0001-0001-0001-100000000001

	column LabResultId
		dataType: string
		summarizeBy: none
		sourceColumn: LabResultId
		lineageTag: 40000010-0001-0001-0001-200000000001

		annotation SummarizationSetBy = Automatic

	column PatientId
		dataType: string
		summarizeBy: none
		sourceColumn: PatientId
		lineageTag: 40000010-0001-0001-0001-200000000002

		annotation SummarizationSetBy = Automatic

	column PhysicianId
		dataType: string
		summarizeBy: none
		sourceColumn: PhysicianId
		lineageTag: 40000010-0001-0001-0001-200000000003

		annotation SummarizationSetBy = Automatic

	column TestType
		dataType: string
		summarizeBy: none
		sourceColumn: TestType
		lineageTag: 40000010-0001-0001-0001-200000000004

		annotation SummarizationSetBy = Automatic

	column TestDate
		dataType: string
		summarizeBy: none
		sourceColumn: TestDate
		lineageTag: 40000010-0001-0001-0001-200000000005

		annotation SummarizationSetBy = Automatic

	column ResultValue
		dataType: double
		summarizeBy: none
		sourceColumn: ResultValue
		lineageTag: 40000010-0001-0001-0001-200000000006

		annotation SummarizationSetBy = Automatic

	column Unit
		dataType: string
		summarizeBy: none
		sourceColumn: Unit
		lineageTag: 40000010-0001-0001-0001-200000000007

		annotation SummarizationSetBy = Automatic

	column ReferenceRange
		dataType: string
		summarizeBy: none
		sourceColumn: ReferenceRange
		lineageTag: 40000010-0001-0001-0001-200000000008

		annotation SummarizationSetBy = Automatic

	column Interpretation
		dataType: string
		summarizeBy: none
		sourceColumn: Interpretation
		lineageTag: 40000010-0001-0001-0001-200000000009

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		summarizeBy: none
		sourceColumn: Status
		lineageTag: 40000010-0001-0001-0001-200000000010

		annotation SummarizationSetBy = Automatic

	partition factlabresult = entity
		mode: directLake
		entityName: factlabresult
		expressionSource: DatabaseQuery

	annotation PBI_ResultType = Table
