table dimaccesspoint
	lineageTag: 20000001-0001-0001-0001-000000000001

	measure 'Access Point Count' = COUNTROWS(dimaccesspoint)
		displayFolder: Measures
		lineageTag: 20000001-0001-0001-0001-100000000001

	column AccessPointId
		dataType: string
		summarizeBy: none
		sourceColumn: AccessPointId
		lineageTag: 20000001-0001-0001-0001-200000000001

		annotation SummarizationSetBy = Automatic

	column AccessPointName
		dataType: string
		summarizeBy: none
		sourceColumn: AccessPointName
		lineageTag: 20000001-0001-0001-0001-200000000002

		annotation SummarizationSetBy = Automatic

	column ZoneId
		dataType: string
		summarizeBy: none
		sourceColumn: ZoneId
		lineageTag: 20000001-0001-0001-0001-200000000003

		annotation SummarizationSetBy = Automatic

	column AccessPointType
		dataType: string
		summarizeBy: none
		sourceColumn: AccessPointType
		lineageTag: 20000001-0001-0001-0001-200000000004

		annotation SummarizationSetBy = Automatic

	column Protocol
		dataType: string
		summarizeBy: none
		sourceColumn: Protocol
		lineageTag: 20000001-0001-0001-0001-200000000005

		annotation SummarizationSetBy = Automatic

	column CoverageAreaSqFt
		dataType: double
		summarizeBy: none
		sourceColumn: CoverageAreaSqFt
		lineageTag: 20000001-0001-0001-0001-200000000006

		annotation SummarizationSetBy = Automatic

	column Manufacturer
		dataType: string
		summarizeBy: none
		sourceColumn: Manufacturer
		lineageTag: 20000001-0001-0001-0001-200000000007

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		summarizeBy: none
		sourceColumn: Status
		lineageTag: 20000001-0001-0001-0001-200000000008

		annotation SummarizationSetBy = Automatic

	partition dimaccesspoint = entity
		mode: directLake
		entityName: dimaccesspoint
		expressionSource: DatabaseQuery

	annotation PBI_ResultType = Table
