table dimlightingsystem
	lineageTag: 20000007-0001-0001-0001-000000000001

	measure 'Lighting System Count' = COUNTROWS(dimlightingsystem)
		displayFolder: Measures
		lineageTag: 20000007-0001-0001-0001-100000000001

	measure 'Total Wattage W' = SUM(dimlightingsystem[WattageTotalW])
		formatString: #,0
		displayFolder: Measures
		lineageTag: 20000007-0001-0001-0001-100000000002

	column LightingId
		dataType: string
		summarizeBy: none
		sourceColumn: LightingId
		lineageTag: 20000007-0001-0001-0001-200000000001

		annotation SummarizationSetBy = Automatic

	column LightingName
		dataType: string
		summarizeBy: none
		sourceColumn: LightingName
		lineageTag: 20000007-0001-0001-0001-200000000002

		annotation SummarizationSetBy = Automatic

	column ZoneId
		dataType: string
		summarizeBy: none
		sourceColumn: ZoneId
		lineageTag: 20000007-0001-0001-0001-200000000003

		annotation SummarizationSetBy = Automatic

	column LightingType
		dataType: string
		summarizeBy: none
		sourceColumn: LightingType
		lineageTag: 20000007-0001-0001-0001-200000000004

		annotation SummarizationSetBy = Automatic

	column WattageTotalW
		dataType: double
		summarizeBy: none
		sourceColumn: WattageTotalW
		lineageTag: 20000007-0001-0001-0001-200000000005

		annotation SummarizationSetBy = Automatic

	column BulbCount
		dataType: double
		summarizeBy: none
		sourceColumn: BulbCount
		lineageTag: 20000007-0001-0001-0001-200000000006

		annotation SummarizationSetBy = Automatic

	column InstallDate
		dataType: string
		summarizeBy: none
		sourceColumn: InstallDate
		lineageTag: 20000007-0001-0001-0001-200000000007

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		summarizeBy: none
		sourceColumn: Status
		lineageTag: 20000007-0001-0001-0001-200000000008

		annotation SummarizationSetBy = Automatic

	partition dimlightingsystem = entity
		mode: directLake
		entityName: dimlightingsystem
		expressionSource: DatabaseQuery

	annotation PBI_ResultType = Table
