table dimzone
	lineageTag: 20000010-0001-0001-0001-000000000001

	measure 'Zone Count' = COUNTROWS(dimzone)
		displayFolder: Measures
		lineageTag: 20000010-0001-0001-0001-100000000001

	measure 'Total Max Occupancy' = SUM(dimzone[MaxOccupancy])
		formatString: #,0
		displayFolder: Measures
		lineageTag: 20000010-0001-0001-0001-100000000002

	column ZoneId
		dataType: string
		summarizeBy: none
		sourceColumn: ZoneId
		lineageTag: 20000010-0001-0001-0001-200000000001

		annotation SummarizationSetBy = Automatic

	column ZoneName
		dataType: string
		summarizeBy: none
		sourceColumn: ZoneName
		lineageTag: 20000010-0001-0001-0001-200000000002

		annotation SummarizationSetBy = Automatic

	column FloorId
		dataType: string
		summarizeBy: none
		sourceColumn: FloorId
		lineageTag: 20000010-0001-0001-0001-200000000003

		annotation SummarizationSetBy = Automatic

	column ZoneType
		dataType: string
		summarizeBy: none
		sourceColumn: ZoneType
		lineageTag: 20000010-0001-0001-0001-200000000004

		annotation SummarizationSetBy = Automatic

	column AreaSqFt
		dataType: double
		summarizeBy: none
		sourceColumn: AreaSqFt
		lineageTag: 20000010-0001-0001-0001-200000000005

		annotation SummarizationSetBy = Automatic

	column MaxOccupancy
		dataType: double
		summarizeBy: none
		sourceColumn: MaxOccupancy
		lineageTag: 20000010-0001-0001-0001-200000000006

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		summarizeBy: none
		sourceColumn: Status
		lineageTag: 20000010-0001-0001-0001-200000000007

		annotation SummarizationSetBy = Automatic

	partition dimzone = entity
		mode: directLake
		entityName: dimzone
		expressionSource: DatabaseQuery

	annotation PBI_ResultType = Table
